import { useState, useEffect } from 'react';
import { authManager } from '../engine/api/authManager.js';

/**
 * Modals
 * All modal overlays from the legacy index.html, rendered as hidden divs.
 * IDs are preserved exactly so the legacy engine can show/hide them with
 * classList.toggle('active') and querySelector('#modal-id') as before.
 */
export default function Modals() {
  const [user, setUser] = useState(authManager.currentUser);

  // Room Creation State
  const [roomName, setRoomName] = useState('');
  const [maxPlayers, setMaxPlayers] = useState(2);
  const [battleType, setBattleType] = useState('singles');
  const [selectedTiers, setSelectedTiers] = useState(['Basic', 'Final']);

  const tierOptions = [
    { id: 'Basic', label: 'Basic' },
    { id: 'Mid', label: 'Mid' },
    { id: 'Final', label: 'Final' },
    { id: 'Legendary', label: 'Legendary' },
    { id: 'Mythical', label: 'Mythical' },
    { id: 'Ultra Beast', label: 'Ultra' },
    { id: 'Mega', label: 'Mega' },
    { id: 'G-Max', label: 'G-Max' },
    { id: 'Alolan', label: 'Alolan' },
    { id: 'Galarian', label: 'Galar' },
    { id: 'Hisuian', label: 'Hisui' },
    { id: 'Paldean', label: 'Paldea' }
  ];

  const toggleTier = (tierId) => {
    setSelectedTiers(prev => 
      prev.includes(tierId) 
        ? prev.filter(t => t !== tierId) 
        : [...prev, tierId]
    );
  };

  // Join Room State
  const [roomCode, setRoomCode] = useState('');
  const [joinRole, setJoinRole] = useState('player');

  // Quick Play State
  const [quickPlayTiers, setQuickPlayTiers] = useState(['Basic', 'Mid', 'Final', 'Legendary', 'Mythical', 'Ultra Beast', 'Alolan', 'Galarian', 'Hisuian', 'Paldean']);

  const toggleQuickPlayTier = (tierId) => {
    setQuickPlayTiers(prev => 
      prev.includes(tierId) 
        ? prev.filter(t => t !== tierId) 
        : [...prev, tierId]
    );
  };

  const handleStartQuickPlay = () => {
    if (!window.arena?.multiplayer) {
        alert('Multiplayer engine not initialized');
        return;
    }
    window.arena.multiplayer.quickBattle({ selectedTiers: quickPlayTiers });
    closeModal('quick-play-modal');
  };

  useEffect(() => {
    const unsub = authManager.subscribe(setUser);
    return unsub;
  }, []);

  const closeModal = (id) => {
    const modal = document.getElementById(id);
    if (modal) {
      modal.classList.remove('active');
      modal.classList.remove('visible'); // keep visible just in case for backward compatibility
    }
  };

  const handleCreateRoom = async () => {
    if (!window.arena?.multiplayer) {
        alert('Multiplayer engine not initialized');
        return;
    }
    try {
        const name = user?.displayName || 'Anonymous';
        const settings = {
            roomName,
            maxPlayers,
            battleType,
            selectedTiers
        };
        const code = await window.arena.multiplayer.createRoom(name, settings);
        console.log('Room created:', code);
        closeModal('room-modal');
    } catch (err) {
        console.error('Create room failed:', err);
        alert('Failed to create room: ' + err.message);
    }
  };

  const handleJoinRoom = async () => {
    const codeToJoin = document.getElementById('room-code-input')?.value || roomCode;
    if (!window.arena?.multiplayer || !codeToJoin) {
        alert('Please enter a room code');
        return;
    }
    const name = user?.displayName || 'Anonymous';
    
    await window.arena.multiplayer.joinRoom(codeToJoin, name, joinRole);
    closeModal('join-modal');
  };

  return (
    <>
      {/* Team Management Modal */}
      <div id="team-modal" className="modal-overlay">
        <div className="modal-content relative overflow-hidden group">
          <div className="absolute top-0 left-0 w-full h-[2px] bg-gradient-to-r from-transparent via-yellow-400/50 to-transparent" />
          <div className="flex justify-between items-center mb-4 border-b-2 border-outline-variant pb-2">
            <h2 id="team-modal-title" className="text-xl font-bold text-yellow-400 font-headline uppercase tracking-tighter text-glow">Manage Team</h2>
            <button onClick={() => closeModal('team-modal')} id="close-team-modal" className="text-secondary hover:text-white transition-colors">
              <span className="material-symbols-outlined text-[24px]">close</span>
            </button>
          </div>
          <div id="team-editor-grid" className="grid grid-cols-3 gap-4 mb-4">
            {/* Slots dynamically generated by JavaScript */}
          </div>
          <div id="pokemon-editor-form" className="bg-surface-container-low border-2 border-outline-variant p-4 mb-4 hidden">
            {/* Dynamically filled by JavaScript */}
          </div>
          <div className="flex justify-end pt-2 border-t-2 border-outline-variant">
            <button id="confirm-team-btn" className="bg-tertiary-container hover:bg-[#5bf083] text-on-tertiary-container px-6 py-3 border-2 border-white font-bold uppercase step-animation hard-shadow-tertiary flex items-center gap-2 text-[10px]">
              <span className="material-symbols-outlined text-[14px]">check</span> DONE
            </button>
          </div>
        </div>
      </div>

      {/* Generic Selection Modal */}
      <div id="selection-modal" className="modal-overlay">
        <div className="modal-content max-w-2xl relative overflow-hidden group">
          <div className="absolute top-0 left-0 w-full h-[2px] bg-gradient-to-r from-transparent via-blue-500/50 to-transparent" />
          <div className="flex justify-between items-center mb-4 border-b-2 border-outline-variant pb-2">
            <h2 id="selection-modal-title" className="text-xl font-bold text-[#699cff] font-headline uppercase tracking-tighter text-glow">Make Selection</h2>
            <button onClick={() => closeModal('selection-modal')} id="close-selection-modal" className="text-secondary hover:text-white transition-colors">
              <span className="material-symbols-outlined text-[24px]">close</span>
            </button>
          </div>
          <div id="selection-grid" className="grid grid-cols-4 gap-4">
            {/* Options dynamically generated by JavaScript */}
          </div>
        </div>
      </div>

      {/* HP Edit Modal */}
      <div id="hp-edit-modal" className="modal-overlay">
        <div className="modal-content max-w-md relative overflow-hidden group">
          <div className="absolute top-0 left-0 w-full h-[2px] bg-gradient-to-r from-transparent via-green-500/50 to-transparent" />
          <div className="flex justify-between items-center mb-4 border-b-2 border-outline-variant pb-2">
            <h3 id="hp-edit-title" className="text-xl text-yellow-400 font-headline uppercase tracking-tighter text-glow">Edit HP</h3>
            <button onClick={() => closeModal('hp-edit-modal')} id="close-hp-edit-modal" className="text-secondary hover:text-white transition-colors">
              <span className="material-symbols-outlined text-[24px]">close</span>
            </button>
          </div>
          <div className="space-y-4 font-body">
            <div className="text-center bg-surface-container-lowest border-2 border-outline-variant p-4">
              <label className="text-[10px] text-on-surface-variant uppercase tracking-wider">Current HP</label>
              <div id="hp-current-display" className="text-4xl font-bold text-white mt-2 font-headline tracking-tighter" />
            </div>
            <div>
              <label className="text-[10px] text-on-surface-variant uppercase tracking-wider block mb-2">Set HP To:</label>
              <input type="number" id="hp-new-value"
                className="w-full bg-surface-container-lowest p-4 text-3xl text-center border-2 border-outline-variant focus:border-yellow-400 focus:ring-0 text-white font-headline"
                min="0" />
              <div className="text-[8px] text-on-surface-variant mt-1 text-center uppercase tracking-wider">Enter value between 0 and max HP</div>
            </div>
            {/* Quick Percentage Buttons */}
            <div>
              <label className="text-[10px] text-on-surface-variant uppercase tracking-wider block mb-2">Quick Set:</label>
              <div className="grid grid-cols-5 gap-2">
                <button className="hp-quick-btn bg-tertiary-container hover:bg-[#5bf083] text-[#004a1d] p-3 text-xs font-bold step-animation border border-white" data-percent="100">100%</button>
                <button className="hp-quick-btn bg-secondary-container hover:bg-[#699cff] text-white p-3 text-xs font-bold step-animation border border-[#003271]" data-percent="75">75%</button>
                <button className="hp-quick-btn bg-primary-container hover:bg-yellow-400 text-on-primary-container p-3 text-xs font-bold step-animation border border-[#685900]" data-percent="50">50%</button>
                <button className="hp-quick-btn bg-[#b92902] hover:bg-[#ff7351] text-[#ffd2c8] p-3 text-xs font-bold step-animation border border-[#450900]" data-percent="25">25%</button>
                <button className="hp-quick-btn bg-black hover:bg-slate-900 text-red-500 p-3 text-xs font-bold step-animation border border-red-500" data-percent="0">0%</button>
              </div>
            </div>
            {/* Confirm / Cancel */}
            <div className="flex gap-2 pt-4 border-t-2 border-outline-variant mt-4">
              <button id="confirm-hp-edit" className="bg-tertiary-container hover:bg-[#5bf083] text-[#004a1d] p-4 w-full font-bold text-sm border-2 border-white step-animation uppercase tracking-wider flex justify-center items-center gap-2">
                <span className="material-symbols-outlined text-[18px]">check</span> CONFIRM
              </button>
              <button onClick={() => closeModal('hp-edit-modal')} id="cancel-hp-edit" className="bg-surface-variant hover:bg-surface-bright text-secondary p-4 w-full font-bold text-sm border-2 border-secondary step-animation uppercase tracking-wider flex justify-center items-center gap-2">
                <span className="material-symbols-outlined text-[18px]">close</span> CANCEL
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* Confirm Modal */}
      <div id="confirm-modal" className="modal-overlay">
        <div className="modal-content max-w-sm relative overflow-hidden group">
          <div className="absolute top-0 left-0 w-full h-[2px] bg-gradient-to-r from-transparent via-red-500/50 to-transparent" />
          <div className="flex justify-between items-center mb-4 border-b-2 border-outline-variant pb-2">
            <h3 id="confirm-modal-title" className="text-xl text-[#ff7351] font-headline uppercase tracking-tighter text-glow">Confirm Action</h3>
            <button onClick={() => closeModal('confirm-modal')} id="close-confirm-modal" className="text-secondary hover:text-white transition-colors">
              <span className="material-symbols-outlined text-[24px]">close</span>
            </button>
          </div>
          <div className="space-y-4 text-center font-body">
            <p id="confirm-modal-message" className="text-white text-sm mb-6">Are you sure?</p>
            <div className="flex gap-2 pt-4 border-t-2 border-outline-variant">
              <button id="confirm-modal-yes" className="bg-[#b92902] hover:bg-[#ff7351] text-white p-3 w-full font-bold text-[10px] border-2 border-[#450900] step-animation uppercase tracking-widest">YES</button>
              <button onClick={() => closeModal('confirm-modal')} id="confirm-modal-no" className="bg-surface-variant hover:bg-surface-bright text-secondary p-3 w-full font-bold text-[10px] border-2 border-secondary step-animation uppercase tracking-widest">NO</button>
            </div>
          </div>
        </div>
      </div>

      {/* Room Creation Modal */}
      <div id="room-modal" className="modal-overlay">
        <div className="modal-content max-w-md relative overflow-hidden group">
          <div className="absolute top-0 left-0 w-full h-[2px] bg-gradient-to-r from-transparent via-yellow-400/50 to-transparent" />
          <div className="flex justify-between items-center mb-4 border-b-2 border-outline-variant pb-2">
            <h2 className="text-xl font-bold text-yellow-400 font-headline uppercase tracking-tighter text-glow">Create Battle Room</h2>
            <button onClick={() => closeModal('room-modal')} id="close-room-modal" className="text-secondary hover:text-white transition-colors">
              <span className="material-symbols-outlined text-[24px]">close</span>
            </button>
          </div>
          <div className="space-y-4 font-body">
            <div>
              <label className="block text-xs font-bold text-slate-300 uppercase tracking-wider mb-2">Room Name:</label>
              <input 
                id="room-name-input" type="text" placeholder="Epic Battle Room..."
                value={roomName}
                onChange={(e) => setRoomName(e.target.value)}
                className="w-full bg-surface-container-lowest border border-outline-variant p-3 text-sm focus:border-yellow-400 focus:ring-0 text-white placeholder:text-[#6d758c]" />
            </div>
            <div>
              <label className="block text-xs font-bold text-slate-300 uppercase tracking-wider mb-2">Max Players:</label>
              <select 
                id="max-players-select" 
                value={maxPlayers}
                onChange={(e) => setMaxPlayers(parseInt(e.target.value))}
                className="w-full bg-surface-container-lowest border border-outline-variant p-3 text-sm focus:border-yellow-400 focus:ring-0 text-white">
                {[2, 3, 4, 5, 6].map(n => <option key={n} value={n}>{n} Players</option>)}
              </select>
            </div>
            <div>
              <label className="block text-xs font-bold text-slate-300 uppercase tracking-wider mb-2">Allowed Tiers:</label>
              <div className="grid grid-cols-3 gap-2 bg-surface-container-low p-3 border border-outline-variant">
                {tierOptions.map(tier => (
                  <button
                    key={tier.id}
                    onClick={() => toggleTier(tier.id)}
                    className={`text-[9px] font-bold uppercase tracking-widest p-2 border transition-all ${
                      selectedTiers.includes(tier.id)
                        ? 'bg-yellow-400 text-black border-yellow-200 shadow-[0_0_10px_rgba(250,204,21,0.5)]'
                        : 'bg-surface-container-lowest text-slate-400 border-outline-variant hover:border-yellow-400/50'
                    }`}
                  >
                    {tier.label}
                  </button>
                ))}
              </div>
              <div className="flex gap-2 mt-2">
                <button 
                  onClick={() => setSelectedTiers(tierOptions.map(t => t.id))}
                  className="text-[8px] text-yellow-400/70 hover:text-yellow-400 uppercase tracking-tighter"
                >
                  Select All
                </button>
                <button 
                  onClick={() => setSelectedTiers([])}
                  className="text-[8px] text-slate-500 hover:text-slate-300 uppercase tracking-tighter"
                >
                  Clear
                </button>
              </div>
            </div>
            <button 
              id="create-room-confirm-btn"
              onClick={handleCreateRoom}
              className="w-full bg-tertiary-container hover:bg-[#5bf083] text-[#004a1d] px-6 py-4 border-2 border-white uppercase font-bold tracking-widest step-animation text-[10px] flex justify-center items-center gap-2 mt-4">
              <span className="material-symbols-outlined text-[18px]">check</span> CREATE ROOM
            </button>
          </div>
        </div>
      </div>

      {/* Quick Play Modal */}
      <div id="quick-play-modal" className="modal-overlay">
        <div className="modal-content max-w-md relative overflow-hidden group">
          <div className="absolute top-0 left-0 w-full h-[2px] bg-gradient-to-r from-transparent via-[#5bf083]/50 to-transparent" />
          <div className="flex justify-between items-center mb-4 border-b-2 border-outline-variant pb-2">
            <h2 className="text-xl font-bold text-[#5bf083] font-headline uppercase tracking-tighter text-glow">Quick Battle Settings</h2>
            <button onClick={() => closeModal('quick-play-modal')} className="text-secondary hover:text-white transition-colors">
              <span className="material-symbols-outlined text-[24px]">close</span>
            </button>
          </div>
          <div className="space-y-4 font-body">
            <div>
              <label className="block text-xs font-bold text-slate-300 uppercase tracking-wider mb-2">Allowed Tiers:</label>
              <div className="grid grid-cols-3 gap-2 bg-surface-container-low p-3 border border-outline-variant">
                {tierOptions.map(tier => (
                  <button
                    key={tier.id}
                    onClick={() => toggleQuickPlayTier(tier.id)}
                    className={`text-[9px] font-bold uppercase tracking-widest p-2 border transition-all ${
                      quickPlayTiers.includes(tier.id)
                        ? 'bg-[#5bf083] text-black border-[#5bf083] shadow-[0_0_10px_rgba(91,240,131,0.5)]'
                        : 'bg-surface-container-lowest text-slate-400 border-outline-variant hover:border-[#5bf083]/50'
                    }`}
                  >
                    {tier.label}
                  </button>
                ))}
              </div>
              <div className="flex gap-2 mt-2">
                <button 
                  onClick={() => setQuickPlayTiers(tierOptions.map(t => t.id))}
                  className="text-[8px] text-[#5bf083]/70 hover:text-[#5bf083] uppercase tracking-tighter"
                >
                  Select All
                </button>
                <button 
                  onClick={() => setQuickPlayTiers([])}
                  className="text-[8px] text-slate-500 hover:text-slate-300 uppercase tracking-tighter"
                >
                  Clear
                </button>
              </div>
            </div>
            <button 
              onClick={handleStartQuickPlay}
              className="w-full bg-tertiary-container hover:bg-[#5bf083] text-[#004a1d] px-6 py-4 border-2 border-white uppercase font-bold tracking-widest step-animation text-[10px] flex justify-center items-center gap-2 mt-4">
              <span className="material-symbols-outlined text-[18px]">bolt</span> START QUICK BATTLE
            </button>
          </div>
        </div>
      </div>

      {/* Join Room Modal */}
      <div id="join-modal" className="modal-overlay">
        <div className="modal-content max-w-md relative overflow-hidden group">
          <div className="absolute top-0 left-0 w-full h-[2px] bg-gradient-to-r from-transparent via-purple-500/50 to-transparent" />
          <div className="flex justify-between items-center mb-4 border-b-2 border-outline-variant pb-2">
            <h2 className="text-xl font-bold text-yellow-400 font-headline uppercase tracking-tighter text-glow">Join Battle Room</h2>
            <button onClick={() => closeModal('join-modal')} id="close-join-modal" className="text-secondary hover:text-white transition-colors">
              <span className="material-symbols-outlined text-[24px]">close</span>
            </button>
          </div>
          <div className="space-y-4 font-body">
            <div>
              <label className="block text-xs font-bold text-slate-300 uppercase tracking-wider mb-2">Enter Room Code:</label>
              <input 
                id="room-code-input" type="text" placeholder="123456" maxLength="6"
                value={roomCode}
                onChange={(e) => setRoomCode(e.target.value)}
                className="w-full bg-surface-container-lowest border border-outline-variant p-4 text-2xl text-center tracking-widest uppercase focus:border-purple-400 focus:ring-0 text-white placeholder:text-[#6d758c] font-headline font-bold" />
              <div className="text-[10px] text-slate-400 mt-2 uppercase tracking-wide text-center">6-digit code provided by room host</div>
            </div>
            <div className="text-sm">
              <p className="mb-2 text-xs font-bold text-slate-300 uppercase tracking-wider">Recent Rooms:</p>
              <div id="recent-rooms-list" className="space-y-2">
                {/* Dynamically populated by JS */}
                <div className="text-center text-[10px] text-slate-400 py-2">Loading recent rooms...</div>
              </div>
            </div>
            <div>
              <label className="block text-xs font-bold text-slate-300 uppercase tracking-wider mb-2">Join As:</label>
              <div className="flex gap-4">
                <label className="flex items-center gap-2 text-sm text-white cursor-pointer">
                  <input 
                    type="radio" name="join-role" value="player" 
                    checked={joinRole === 'player'}
                    onChange={() => setJoinRole('player')}
                    className="accent-purple-500" />
                  Player
                </label>
                <label className="flex items-center gap-2 text-sm text-white cursor-pointer">
                  <input 
                    type="radio" name="join-role" value="spectator" 
                    checked={joinRole === 'spectator'}
                    onChange={() => setJoinRole('spectator')}
                    className="accent-purple-500" />
                  Spectator
                </label>
              </div>
            </div>
            <button 
              id="join-room-confirm-btn"
              onClick={handleJoinRoom}
              className="w-full bg-[#9333ea] hover:bg-purple-500 text-white px-6 py-4 border-2 border-[#581c87] uppercase font-bold tracking-widest step-animation text-[10px] flex justify-center items-center gap-2 mt-4">
              <span className="material-symbols-outlined text-[18px]">group</span> JOIN ROOM
            </button>
          </div>
        </div>
      </div>

      {/* Settings Modal */}
      <div id="settings-modal" className="modal-overlay">
        <div className="modal-content max-w-md relative overflow-hidden group">
          <div className="absolute top-0 left-0 w-full h-[2px] bg-gradient-to-r from-transparent via-slate-400/50 to-transparent" />
          <div className="flex justify-between items-center mb-4 border-b-2 border-outline-variant pb-2">
            <h2 className="text-xl font-bold text-yellow-400 font-headline uppercase tracking-tighter text-glow">Settings</h2>
            <button onClick={() => closeModal('settings-modal')} id="close-settings-modal" className="text-secondary hover:text-white transition-colors">
              <span className="material-symbols-outlined text-[24px]">close</span>
            </button>
          </div>
          <div className="space-y-6 font-body">
            <div>
              <label className="flex justify-between items-center text-[10px] text-on-surface-variant uppercase tracking-wider mb-2">
                <span>Volume</span>
                <span id="volume-display" className="text-white font-bold bg-surface-container px-2 py-1 border border-outline-variant">50%</span>
              </label>
              <input id="volume-slider" type="range" min="0" max="100" defaultValue="50" className="w-full accent-yellow-400 h-2 bg-surface-container-lowest outline-none" />
            </div>
            <div>
              <label className="block text-[10px] text-on-surface-variant uppercase tracking-wider mb-2">Animation Speed</label>
              <select id="animation-speed-select" className="w-full bg-surface-container-lowest border border-outline-variant p-3 text-sm focus:border-yellow-400 focus:ring-0 text-white">
                <option value="0.5">Slow (0.5x)</option>
                <option value="1" defaultValue>Normal (1x)</option>
                <option value="1.5">Fast (1.5x)</option>
                <option value="2">Very Fast (2x)</option>
              </select>
            </div>
            <div className="flex items-center gap-3 bg-surface-container-low p-3 border border-outline-variant cursor-pointer hover:bg-surface-variant transition-colors"
              onClick={() => document.getElementById('autosave-checkbox').click()}>
              <input id="autosave-checkbox" type="checkbox" defaultChecked className="w-4 h-4 accent-yellow-400 cursor-pointer" />
              <label className="text-[10px] text-white uppercase tracking-wider font-bold cursor-pointer">Enable Autosave</label>
            </div>
            <div className="flex items-center gap-3 bg-surface-container-low p-3 border border-outline-variant cursor-pointer hover:bg-surface-variant transition-colors"
              onClick={() => document.getElementById('damage-numbers-checkbox').click()}>
              <input id="damage-numbers-checkbox" type="checkbox" defaultChecked className="w-4 h-4 accent-yellow-400 cursor-pointer" />
              <label className="text-[10px] text-white uppercase tracking-wider font-bold cursor-pointer">Show Damage Numbers</label>
            </div>
            <button id="save-settings-btn"
              className="w-full bg-tertiary-container hover:bg-[#5bf083] text-[#004a1d] px-6 py-4 border-2 border-white uppercase font-bold tracking-widest step-animation text-[10px] flex justify-center items-center gap-2 mt-2">
              <span className="material-symbols-outlined text-[18px]">save</span> SAVE SETTINGS
            </button>
          </div>
        </div>
      </div>

      {/* Multiplayer Lobby Modal */}
      <div id="multiplayer-lobby-modal" className="modal-overlay">
        <div className="modal-content max-w-2xl relative overflow-hidden group">
          <div className="absolute top-0 left-0 w-full h-[2px] bg-gradient-to-r from-transparent via-[#699cff]/50 to-transparent" />
          <div className="flex justify-between items-center mb-6 border-b-2 border-outline-variant pb-3">
            <div className="flex items-center gap-3">
              <span className="material-symbols-outlined text-[#699cff] text-[28px]" style={{ fontVariationSettings: "'FILL' 1" }}>public</span>
              <h2 className="text-2xl font-bold text-yellow-400 font-headline uppercase tracking-tighter text-glow">Multiplayer Lobby</h2>
            </div>
            <button onClick={() => window.arena?.multiplayer?.leaveRoom()} className="text-secondary hover:text-white transition-colors">
              <span className="material-symbols-outlined text-[28px]">logout</span>
            </button>
          </div>
          <div className="modal-body md:flex gap-6">
            {/* Left Column */}
            <div className="flex-1 space-y-6">
              <div className="room-code-section bg-surface-container-low border-2 border-outline-variant p-5 text-center">
                <h3 className="text-[10px] text-on-surface-variant uppercase tracking-widest mb-3">Room Code</h3>
                <div id="room-code-display" className="room-code text-5xl font-headline text-yellow-400 tracking-[0.2em] text-glow mb-4 bg-surface-container-lowest py-4 border border-outline-variant inline-block w-full">ABC123</div>
                <p className="text-[8px] text-on-surface-variant uppercase tracking-wider mb-4">Share this code with friends to join</p>
                <div className="flex gap-3 justify-center">
                  <button id="copy-code-btn" onClick={() => window.copyRoomCode?.()}
                    className="bg-primary-container hover:bg-yellow-400 text-on-primary-container font-bold py-2 px-4 border border-[#685900] text-[10px] uppercase tracking-wider flex items-center gap-2 step-animation">
                    <span className="material-symbols-outlined text-[14px]">content_copy</span> Copy Code
                  </button>
                  <button id="share-link-btn" onClick={() => window.shareRoomLink?.()}
                    className="bg-secondary-container hover:bg-[#699cff] text-white font-bold py-2 px-4 border border-[#003271] text-[10px] uppercase tracking-wider flex items-center gap-2 step-animation">
                    <span className="material-symbols-outlined text-[14px]">share</span> Share Link
                  </button>
                </div>
                <p id="copy-feedback" className="text-[10px] font-bold uppercase tracking-wider text-[#5bf083] mt-3 hidden">Copied to clipboard!</p>
              </div>
              <div className="p-4 bg-surface-variant border border-outline-variant flex gap-3 text-secondary">
                <span className="material-symbols-outlined text-yellow-400">lightbulb</span>
                <p className="text-[10px] uppercase tracking-wider leading-relaxed">
                  Wait for all players to join, then click "Toggle Ready". Host can start the game when everyone is ready.
                </p>
              </div>
            </div>
            {/* Right Column */}
            <div className="flex-1 mt-6 md:mt-0 flex flex-col">
              <div className="players-section bg-surface-container border-2 border-outline-variant flex-1 flex flex-col">
                <div className="bg-surface-container-high px-4 py-2 border-b-2 border-outline-variant flex justify-between items-center">
                  <h3 className="text-[10px] text-on-surface-variant uppercase tracking-widest font-bold">Players in Room</h3>
                  <select id="rng-tier-select" className="bg-surface-container-lowest text-[8px] text-yellow-400 border border-outline-variant p-1 uppercase tracking-widest outline-none focus:border-yellow-400" style={{ display: 'none' }}>
                    <option value="any">Any Tier</option>
                    <option value="OU">OU (Overused)</option>
                    <option value="UU">UU (Underused)</option>
                    <option value="Uber">Uber</option>
                  </select>
                </div>
                <div id="room-player-list" className="p-3 space-y-2 overflow-y-auto flex-1 max-h-[250px] font-body">
                  <div className="flex justify-between items-center bg-surface-container-lowest p-3 border border-outline-variant">
                    <span className="text-white text-sm font-bold">Player 1 (Host)</span>
                    <span className="text-[#5bf083] text-[10px] uppercase tracking-wider border border-[#004a1d] bg-[#004a1d]/30 px-2 py-1">Ready</span>
                  </div>
                </div>
              </div>
              <div className="controls mt-4 flex gap-3">
                <button id="ready-btn" onClick={() => window.arena?.multiplayer?.toggleReady()}
                  className="flex-1 bg-secondary-container hover:bg-[#699cff] text-white font-bold py-4 px-4 border-2 border-white step-animation uppercase tracking-widest text-xs hard-shadow-secondary flex justify-center items-center gap-2">
                  <span className="material-symbols-outlined">rule</span> Toggle Ready
                </button>
                <button id="start-game-btn" onClick={() => window.arena?.multiplayer?.startGame()}
                  className="flex-1 bg-tertiary-container hover:bg-[#5bf083] text-[#004a1d] font-bold py-4 px-4 border-2 border-white step-animation uppercase tracking-widest text-xs overflow-hidden relative"
                  style={{ display: 'none', boxShadow: '4px 4px 0px 0px #004a1d' }}>
                  <div className="absolute inset-0 bg-white/20 hover:bg-transparent transition-colors" />
                  <span className="material-symbols-outlined inline-block relative z-10">sports_esports</span>
                  <span className="relative z-10">Start Game</span>
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
      {/* Load Game Modal */}
      <div id="load-modal" className="modal-overlay">
        <div className="modal-content max-w-2xl relative overflow-hidden group">
          <div className="absolute top-0 left-0 w-full h-[2px] bg-gradient-to-r from-transparent via-[#5bf083]/50 to-transparent" />
          <div className="flex justify-between items-center mb-6 border-b-2 border-outline-variant pb-3">
            <div className="flex items-center gap-3">
              <span className="material-symbols-outlined text-[#5bf083] text-[28px]" style={{ fontVariationSettings: "'FILL' 1" }}>cloud_download</span>
              <div>
                <h2 className="text-2xl font-bold text-yellow-400 font-headline uppercase tracking-tighter text-glow">Load Game</h2>
                <p className="text-[9px] text-slate-400 uppercase tracking-widest mt-0.5">Your last 20 cloud saves — click any to resume</p>
              </div>
            </div>
            <button
              onClick={() => closeModal('load-modal')}
              className="text-secondary hover:text-white transition-colors">
              <span className="material-symbols-outlined text-[28px]">close</span>
            </button>
          </div>

          {/* Save cards grid */}
          <div
            id="load-game-list"
            className="grid grid-cols-1 sm:grid-cols-2 gap-3 max-h-[60vh] overflow-y-auto pr-1 font-body">
            {/* Populated by loadSavedGames() inside socketClient.js */}
            <div className="text-center text-[10px] text-slate-400 py-8 col-span-2">Loading saves…</div>
          </div>

          <div className="mt-4 pt-3 border-t-2 border-outline-variant flex justify-between items-center">
            <p className="text-[9px] text-slate-500 uppercase tracking-wider">
              Saves are stored per account on Firebase — each player keeps their own copy
            </p>
            <button
              onClick={() => closeModal('load-modal')}
              className="bg-surface-variant hover:bg-surface-bright text-secondary px-4 py-2 border border-secondary font-bold text-[9px] uppercase tracking-widest step-animation">
              CLOSE
            </button>
          </div>
        </div>
      </div>
    </>
  );
}
